[pytest]
# 1. 命令行默认启动参数（解决每次手打 -vs 和控制台杂乱的问题）
# -v: 显示详细打印（用例名字、Pass/Fail 状态）
# -s: 允许显示代码里的 print() 输出
# --tb=short: 用例报错时，只显示精简的错误栈，不打印一大堆冗余的源码（控屏变干净的关键！）
# --disable-warnings: 隐藏无用的 Python/库的 Warning 警告提示，干净利落
addopts = -vs --tb=short --disable-warnings

# 2. 告诉 Pytest 你的用例去哪个文件夹找（根据你的项目目录改，比如 test_cases）
testpaths = test_cases

# 3. 命名自动识别规则（Pytest 默认规则）
python_files = test_*.py
python_classes = Test*
python_functions = test_*